# ASP.NET Core

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

variables:
  major: '1'
  minor: '0'
  patch: '0'

resources:
  containers:
  - container: ora
    connection: AzureContainers
    image: mrginfocontainerregistry.azurecr.io/ado-query/ora
    ports:
    - '1521:1521'
  - container: sql
    connection: AzureContainers
    image: mrginfocontainerregistry.azurecr.io/ado-query/sql
    ports:
    - '1433:1433'

pool:
  vmImage: 'ubuntu-latest'

services:
  ora: ora
  sql: sql

steps:
- task: Delay@1
  displayName: 'Wait for services'
  inputs:
    delayForMinutes: '6'
- task: DotNetCoreCLI@2
  displayName: 'Run unit tests'
  inputs:
    command: 'test'
    projects: '**/*.Test.csproj'
    #arguments: '--filter DisplayName~FakeSqlProviderTests'
- task: PublishTestResults@2
  displayName: 'Publish test results'
  inputs:
    testResultsFormat: 'XUnit'
    testResultsFiles: '**/*.trx'
    mergeTestResults: true
- task: DotNetCoreCLI@2
  displayName: 'Create package'
  inputs:
    command: 'pack'
    packagesToPack: '**/MrgInfo.AdoQuery.Core.csproj;**/MrgInfo.AdoQuery.Sql.csproj;**/MrgInfo.AdoQuery.Oracle.csproj'
    versioningScheme: 'byPrereleaseNumber'
    majorVersion: '$(major)'
    minorVersion: '$(minor)'
    patchVersion: '$(patch)'
- task: NuGetCommand@2
  displayName: 'Push to nuget.org'
  inputs:
    command: 'push'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'NuGet'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
