# ASP.NET Core

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  major: '1'
  minor: '0'
  patch: '0'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Run unit tests'
  inputs:
    command: 'test'
    projects: '**/*.Test.csproj'
    arguments: '--filter DisplayName~FakeSqlProviderTests'
- task: PublishTestResults@2
  displayName: 'Publish test results'
  inputs:
    testResultsFormat: 'XUnit'
    testResultsFiles: '**/*.trx'
    mergeTestResults: true
    buildConfiguration: '$(buildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: 'Create package'
  inputs:
    command: 'pack'
    packagesToPack: '**/MrgInfo.AdoQuery.Core.csproj;**/MrgInfo.AdoQuery.Sql.csproj;**/MrgInfo.AdoQuery.Oracle.csproj'
    versioningScheme: 'byPrereleaseNumber'
    majorVersion: '$(major)'
    minorVersion: '$(minor)'
    patchVersion: '$(patch)'
- task: NuGetCommand@2
  displayName: 'Push to nuget.org'
  inputs:
    command: 'push'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'NuGet'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
