# https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema
name: $(Date:yyyyMMdd)$(Rev:.r)
resources:
  containers:
  - container: ora
    image: mrginfocontainerregistry.azurecr.io/ado-query/ora
    endpoint: AzureContainers
    options: --health-start-period=5m 
    ports:
    - '1521:1521'
  - container: sql
    image: mrginfocontainerregistry.azurecr.io/ado-query/sql
    endpoint: AzureContainers
    options: --health-start-period=5m
    ports:
    - '1433:1433'
variables:
  packageVersion: 1.0.0
trigger:
- master
jobs:
- job: packages
  displayName: Build and test packages
  #dependsOn: images
  pool:
    vmImage: ubuntu-latest
  services:
    ora: ora
    sql: sql
  steps:
  - pwsh: Start-Sleep -s (2*60)
    displayName: Wait for database servers to boot
  - task: DotNetCoreCLI@2
    displayName: Run unit tests
    inputs:
      command: test
      projects: '**/MrgInfo.AdoQuery.Test.csproj'
      verbosityPack: detailed
  - task: DotNetCoreCLI@2
    displayName: Create package
    inputs:
      command: pack
      packagesToPack: '**/MrgInfo.AdoQuery.Core.csproj;**/MrgInfo.AdoQuery.Sql.csproj;**/MrgInfo.AdoQuery.Oracle.csproj'
      versioningScheme: byEnvVar
      versionEnvVar: packageVersion
      verbosityPack: detailed
  - task: NuGetCommand@2
    displayName: Push to nuget.org
    inputs:
      command: push
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
      nuGetFeedType: external
      publishFeedCredentials: NuGet
