# ASP.NET Core

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*.Test.csproj'
    arguments: '--filter DisplayName~FakeSqlProviderTests'
    testRunTitle: 'Uni test'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'XUnit'
    testResultsFiles: '**/*.trx'
    mergeTestResults: true
    buildConfiguration: '$(buildConfiguration)'