version: "3.7"
services:
  oracle:
    #image: container-registry.oracle.com/database/enterprise:12.2.0.1
    build: ./MrgInfo.AdoQuery.Oracle
    ports:
      - "1521:1521"
      - "5500:5500"


# sqlplus sys/Oradoc_db1@'(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=localhost)(PORT=1521))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=ORCLPDB1.localdomain))))' as sysdba


sqlplus sys/Oradoc_db1@localhost/ORCL