version: "3.7"
services:
    # cd ./MrgInfo.AdoQuery.Oracle
    # docker build -t ora:latest .
    # docker run -p 1521:1521 --name ora ora:latest
    # docker inspect --format="{{if .Config.Healthcheck}}{{print .State.Health.Status}}{{end}}" ora
    # docker exec ora cat /home/oracle/dba/database.log
    # docker rm -f ora
    oracle:
        build: ./MrgInfo.AdoQuery.Oracle
        image: ora:latest
        container_name: ora
        ports:
            - "1521:1521"

    # cd ./MrgInfo.AdoQuery.Sql
    # docker build -t sql:latest .
    # docker run -p 1433:1433 --name sql sql:latest
    # docker inspect --format="{{if .Config.Healthcheck}}{{print .State.Health.Status}}{{end}}" sql
    # docker exec sql cat /root/dba/database.log
    # docker rm -f sql
    sql:
        build: ./MrgInfo.AdoQuery.Sql
        image: sql:latest
        container_name: sql
        ports:
            - "1433:1433"
